config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  devise_for :users
  devise_scope :user  do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :destroy
    get 'edit', to: 'devise/registrations#edit', as: :edit
    get 'users', to: 'users#index', as: :users
  end
  
resources :users
  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show'

mount Commontator::Engine => '/commontator'

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  include Pundit
  include Commontator
  before_filter :authenticate_user!, only: [:new, :create, :update, :destroy]
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name, :content, :user_id)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class:"form-horizontal"}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id }%>
  <%= f.input :content %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="page-header">
  <h1 class="brand"> The Center of the Universe </h1>
</div>
<div class ="new_stat_btt">
<%= link_to "Post a New Status", new_status_path, class:"btn btn-success" %>
</div>
<% @statuses.each do |status| %>
<div class="status">
  <div class = "row">
    <div class = "span1">
      <%= image_tag status.user.gravitar_url %>
    </div>
    <div class="span7">
    <strong><%= link_to status.user.profile_name, status.user.profile_name %></strong>
      <p> <%=status.content %><p>
      </div>
        <div class ="meta">
          <%= link_to time_ago_in_words(status.created_at)+" ago", status %>
          <% if user_signed_in? %>
         
          <% if status.user == current_user or current_user.admin? %>
            <div class="admin">
              | <%= link_to "Edit Status", edit_status_path(status) %> |
              <%= link_to "Delete Status",status,method: :delete, data: {confirm:"Are you sure you want to delete this status?"} %>
            </div>
          <% end %>
          
          <%# necessary for usage of commontator gem & changed the order of codes from line 20 to line 28~yj %>
          <%= commontator_thread(status) %> 

          <% end %>
      </div>
    </div>
</div>
<%end %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @status.user.profile_name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>