config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  devise_for :users
  devise_scope :user  do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :destroy
    get 'edit', to: 'devise/registrations#edit', as: :edit
    get 'users', to: 'users#index', as: :users
  end
  
resources :users
  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show'

mount Commontator::Engine => '/commontator'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-fixed-top"> 
		<div class="navbar-inner">
			<div class = "container">
				<a class="brand"href="feed"> ProjectBook 
				</a>
				<ul class="nav">
					<li> <%= link_to"All Statuses", feed_path %> </li>
				</ul>
				<ul class="nav pull-right">

					<% if user_signed_in? %>
					  	<% if current_user.admin? %>
    						<li><%= link_to 'Users', users_path %></li>
  						<% end %>
					<li> <%= link_to current_user.first_name, edit_path %> </li>
					<li> <%= link_to "Logout", destroy_path %> </li>
					<% else %>
						<li> <%= link_to "Register", register_path %> </li>
						<li> <%= link_to "Log In", login_path %> </li>
					<% end %>
				</ul> 
			</div>
		</div>
	</div>
	<div class= "container">
		<% flash.each do |type,message| %>
			<div class = "alert <%= flash_class type %>" >
				<button class = "close" data-dismiss = "alert">x</button>
				<%= message %>
			</div>

		<%end%>
		<%= yield %>
	</div>
</body>
</html>